# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='city',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='country',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='province',
        ),
        migrations.AddField(
            model_name='poi',
            name='location',
            field=geoposition.fields.GeopositionField(default=None, max_length=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poi',
            name='status',
            field=models.CharField(choices=[('nominal', 'Nominal'), ('onair', 'On Air')], max_length=50),
        ),
    ]
