# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('pois', '0002_auto_20161229_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region'),
            preserve_default=False,
        ),
    ]
