# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0003_auto_20161229_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='poi_type',
        ),
        migrations.AlterField(
            model_name='poi',
            name='activity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='activity_duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='avg_move_in_floor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='days',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='floor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poi',
            name='rush_hours',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='staff_count',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='status',
            field=models.CharField(choices=[('nominal', 'Nominal'), ('sa_done', 'S.A Done'), ('ap_installation_done', 'A.P.Installation.Done'), ('bh_installation_done', 'B.H.Installation.Done'), ('onair', 'On - Air'), ('switched_off', 'Switched Off'), ('undefined', 'undefined')], max_length=50),
        ),
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=30, null=True),
        ),
    ]
