# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0004_auto_20161231_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='status',
            field=models.CharField(blank=True, choices=[('nominal', 'Nominal'), ('sa_done', 'S.A Done'), ('ap_installation_done', 'A.P.Installation.Done'), ('bh_installation_done', 'B.H.Installation.Done'), ('onair', 'On - Air'), ('switched_off', 'Switched Off')], max_length=50, null=True),
        ),
    ]
