# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0005_auto_20161231_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_persian', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='poi',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pois.Status'),
        ),
    ]
