# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 16:20
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0007_auto_20170127_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=colorful.fields.RGBColorField(default=0),
            preserve_default=False,
        ),
    ]
