# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 17:32
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


def load_fields(apps, schema_editor):
    Poi = apps.get_model("pois", "Poi")
    AvailableField = apps.get_model("pois", "AvailableField")
    db_alias = schema_editor.connection.alias
    AvailableField.objects.using(db_alias).bulk_create(
        [
            AvailableField(name=t.name) for t in Poi._meta.get_fields()
            ])

def reverse(apps, schema_editor):
    return None

class Migration(migrations.Migration):
    dependencies = [
        ('pois', '0008_add_color_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(load_fields, reverse),
        migrations.CreateModel(
            name='DisplayRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.ManyToManyField(to='pois.AvailableField')),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=colorful.fields.RGBColorField(default='#808080'),
        ),
    ]
