# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0009_auto_20170127_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayrole',
            name='statuses',
            field=models.ManyToManyField(to='pois.Status'),
        ),
    ]
