# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0011_auto_20170213_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablefield',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
